timeline
title  Programme de formation : Web et Mobile

section Sas - 2 semains
    2 semains: Outillage 
            : Gestion de version 
            : Documentation
            : HTML et CSS 
            : Modélisation
            : Programmation
section Web et Mobile - 4 mois
    Lundi,Mardi - Web : Conception projet individuel
        : Autoformation - laravel (Model,Repository,API)
        : Gestion de projet
        : Mardi après-midi (Ateliers - Algorithme,JS,SQL,LAN)
        : Mini-projet - API pour projet individuel
        : CC1 ( Backend, Maquettage, Gestion projet)
    Jeudi,Vendredi - Mobile : Kotlin, POO, debugage
        : CC1 - Kotlin,POO
        : Programmation par compsants
        : CC2 - Une interface de projet individuel
        : mini-projet (Affichage de Météo)
        : EFM - Une interface de projet individuel
section Web - 5 mois
    5 mois: Maquettage
        : Lancement de projet collaborative
        : Backend
        : Database
        : Gestion de projet
        : Unit-test
        : Déploiement

section Projet fin de formation - 1 mois
    1 mois: projet file rouge
